application: sgpura
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /admin/.*
  script: google.appengine.ext.admin.application
  login: admin

- url: /.*
  script: manage.application

libraries:
- name: django
  version: latest

- name: lxml
  version: latest

- name: numpy
  version: latest

builtins:
- remote_api: on
- admin_redirect: on
- appstats: on
