application: sgpura
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: manage.application

libraries:
- name: django
  version: latest

- name: lxml
  version: latest
